# https://github.com/camunda-community-hub/spring-zeebe#configuring-camunda-platform-8-saas-connection
# https://github.com/camunda-community-hub/spring-zeebe#additional-configuration-options
zeebe:
  client:
    cloud:
      cluster-id: xxx
      client-id: xxx
      client-secret: xxx
      region: bru-2